### ISSUE TITLE
How to visualize the output?

### ISSUE THREAD

**Issue by AntonioMarsella** [xigt/freki#14]
Hi,

thanks for the awesome work!

Do you have a script for visualizing the output as in the example you have shown?

Thank you

**Comment by goodmami** [comment]
Thanks!

Sorry it's not very clear. The visualization is created when running the script with the `--debug` option (mentioned in the [usage description](https://github.com/xigt/freki#usage)). Note that matplotlib will need to be installed. Give that a try?

**Comment by AntonioMarsella** [comment]
Great, it worked!

Thank you

**Comment by goodmami** [comment]
Great! I haven't touched this code in some time so I'm not sure how much help I can be in general, but let us know if you have any more questions. Cheers
