### ISSUE TITLE
Is it possible to crop a pdf and then save as pdf?

### ISSUE THREAD

**Issue by AntonioMarsella** [xigt/freki#16]
Hi,
I need to use the pdfminer pdf2txt.py script, so I think I need to save the cropped pdf that I get from here. Is there a way to save a cropped single page into a .pdf format file?

Thank you

**Comment by goodmami** [comment]
Hi, it looks like you immediately closed the issue, so maybe you figured something out, but if you need to get a subset of pages from PDFs you can use something like [pdfjam](https://github.com/DavidFirth/pdfjam). If you want to crop part of a PDF page (e.g., to get a figure or a paragraph) you might find the [clipdf](https://github.com/xigt/clipdf) tool I wrote to be useful (it's just a wrapper around ghostscript). Both of these require a Linux-like system, though.
